CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "first_name" varchar NOT NULL,
  "last_name" varchar NOT NULL,
  "email" varchar NOT NULL,
  "password" varchar NOT NULL,
  "phone" varchar,
  "birthday" date DEFAULT '2000/01/01'
);

CREATE TABLE "coursers" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar NOT NULL,
  "description" varchar NOT NULL,
  "level" varchar NOT NULL,
  "teacher" varchar NOT NULL,
  "id_categories" int
);

CREATE TABLE "courser_video" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar NOT NULL,
  "video_url" varchar NOT NULL,
  "id_courser" int
);

CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name_categoria" varchar NOT NULL
);

CREATE TABLE "users_courser" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_courser" int,
  "id_user" int
);

ALTER TABLE "users_courser" ADD FOREIGN KEY ("id_user") REFERENCES "users" ("id");

ALTER TABLE "users_courser" ADD FOREIGN KEY ("id_courser") REFERENCES "coursers" ("id");

ALTER TABLE "coursers" ADD FOREIGN KEY ("id_categories") REFERENCES "categories" ("id");

ALTER TABLE "courser_video" ADD FOREIGN KEY ("id_courser") REFERENCES "coursers" ("id");

--tabla users

insert into users (
first_name,
last_name,
email,
"password",
phone 
) values (
'Richard',
'yarleque',
'richard@academlo.com',
'root',
'123456789'
); 

insert into users (
first_name,
last_name,
email,
"password",
phone 
) values (
'Emily',
'yarleque',
'emily@academlo.com',
'root',
'234567890'
); 

insert into users (
first_name,
last_name,
email,
"password",
phone 
) values (
'Roxana',
'zegarra',
'roxana@academlo.com',
'root',
'345678901'
); 
 --tabla courser

insert into coursers (
title,
description,
level,
teacher
) values (
'JavaScript',
'JavaScript es un lenguaje de programación ',
'Basico',
'E.R.Y.B.'
); 

insert into coursers (
title,
description,
level,
teacher
) values (
'CSS',
'Es un lenguaje de reglas de estilo',
'Intermedio',
'Y.B.'
); 

insert into coursers (
title,
description,
level,
teacher
) values (
'HTML',
'Usamos para estructurar ',
'Avanzado',
'Y.B.'
);

-- tabla courser_video

insert into courser_video (
title,
video_url
) values (
'HTML',
'https://www.youtube.com/watch?v=MJkdaVFHrto&t=16s'

);

insert into courser_video (
title,
video_url
) values (
'Javascript',
'https://www.youtube.com/watch?v=z95mZVUcJ-E&t=29622s'

);
insert into courser_video (
title,
video_url
) values (
'CSS',
'https://www.youtube.com/watch?v=3yM5uXp-T_0'

);

--tabla categories
insert into categories(
name_categoria
)values (
'Programacion'
);


insert into categories(
name_categoria
)values (
'Programacion'
);


insert into categories(
name_categoria
)values (
'Programacion'
);


--tabla users_courser 

insert into users_courser( 
id_courser,
id_user
)
values(
'02',
'01'
);

insert into users_courser( 
id_courser,
id_user
)
values(
'01',
'03'
);

insert into users_courser( 
id_courser,
id_user
)
values(
'02',
'03'
);

